# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'

    - name: Build
      run: |
        npm ci
        npm run build
    - name: Archive artifact
      shell: sh
      if: runner.os == 'Linux'
      run: |
        chmod -c -R +rX "$INPUT_PATH" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
        tar \
          --dereference --hard-dereference \
          --directory "$INPUT_PATH" \
          -cvf "$RUNNER_TEMP/github-pages.tar" \
          --exclude=.git \
          --exclude=.github \
          .
      env:
        INPUT_PATH: build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: "$RUNNER_TEMP/github-pages.tar"
  
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download production build
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: github-pages.tar
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload build folder
          path: github-pages.tar
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
